apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded value of 'root'
  MYSQL_DATABASE: bXlfZGI=  # base64 encoded value of 'my_db'
  MYSQL_USER: bXl1c2Vy  # base64 encoded value of 'myuser'
  MYSQL_PASSWORD: bXlwYXNzd29yZA==  # base64 encoded value of 'mypassword'
