apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secrets
type: Opaque
data:
  DB_USERNAME: bXl1c2Vy  # Base64 encoded value of 'myuser'
  DB_PASSWORD: bXlwYXNzd29yZA==  # Base64 encoded value of 'mypassword'
  DB_NAME: bXlfZGI=  # Base64 encoded value of 'my_db'
  DB_HOST: bXlzcWw=  # Base64 encoded value of 'mysql'
