apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: minhaz71/nodejs-mysql-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
        - name: DB_NAME
          value: my_db
        - name: DB_HOST
          value: mysql
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007  
  
